name: takly
description: A new Flutter project.
publish_to: 'none'  

   
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2
  easy_splash_screen: ^1.0.4
  firebase_core: ^2.16.0
  flutterfire_cli: ^0.3.0-dev.18

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/App_Icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21  
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

 
flutter:

  
  uses-material-design: true

  assets:
    - assets/images/App_Icon/icon.png
    - assets/images/Icon_Button/Apple.png
    - assets/images/Icon_Button/Facebook.png
    - assets/images/Icon_Button/iconGoogle.png
    - assets/images/Main_Image/Talky_2.png
    - assets/images/Main_Image/Talky.png
    - assets/images/Main_Image/Rectangle 2161.png
    - assets/images/Main_Image/User_Active.png

  

     
   # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
   
   
