name: takly
description: A new Flutter project.
publish_to: 'none'  

   
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2
  easy_splash_screen: ^1.0.3
  firebase_core: ^2.16.0
  flutterfire_cli: ^0.3.0-dev.18
  google_sign_in: ^6.1.5
  firebase_auth: ^4.10.1
  flutter_facebook_auth: ^5.0.11
  sms_otp_auto_verify: ^2.1.0
  sms_autofill: ^2.0.0
  random_string: ^2.3.1
  intl_phone_number_input: ^0.7.0
  cloud_firestore: ^4.9.3
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  get: ^4.6.6
  twitter_login: ^4.4.0
  image_picker: ^1.0.4
  firebase_storage: ^11.2.8

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/App_Icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21  
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

 
flutter:

  
  uses-material-design: true

  assets:
    - assets/images/App_Icon/icon.png
    - assets/images/Icon_Button/Apple.png
    - assets/images/Icon_Button/Facebook.png
    - assets/images/Icon_Button/iconGoogle.png
    - assets/images/Main_Image/Talky_2.png
    - assets/images/Main_Image/Talky.png
    - assets/images/Main_Image/Rectangle 2161.png
    - assets/images/Main_Image/User_Active.png
    - assets/images/Main_Image/User_190px.png
    - assets/images/Main_Image/twitter.png
    - assets/images/Main_Image/no_image.jpg

  

     
   # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
   
   
