// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN0ONQZ10mTebkjKS7g-ITIpT864OMsnw',
    appId: '1:576186524532:web:dd03dba6f0d5b5df914221',
    messagingSenderId: '576186524532',
    projectId: 'takly-d5125',
    authDomain: 'takly-d5125.firebaseapp.com',
    storageBucket: 'takly-d5125.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSj5BeAYMy0LGmsXWRBYXUcNX4142NNKM',
    appId: '1:576186524532:android:864c1b8eb7b42b9e914221',
    messagingSenderId: '576186524532',
    projectId: 'takly-d5125',
    storageBucket: 'takly-d5125.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNyYMujg0urvbgaKW2koddYfMTcY_c7pM',
    appId: '1:576186524532:ios:08fef0f722507be9914221',
    messagingSenderId: '576186524532',
    projectId: 'takly-d5125',
    storageBucket: 'takly-d5125.appspot.com',
    iosClientId: '576186524532-eg8f32e7fp6jin0ec7hmbomnh1d82mh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.takly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNyYMujg0urvbgaKW2koddYfMTcY_c7pM',
    appId: '1:576186524532:ios:a3e92b1fded8fe17914221',
    messagingSenderId: '576186524532',
    projectId: 'takly-d5125',
    storageBucket: 'takly-d5125.appspot.com',
    iosClientId: '576186524532-q28h75olcuuo01e039vhu2bddmka6lsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.takly.RunnerTests',
  );
}
